import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutContainer from "./LayoutContainer";


const inter = Inter({ subsets: ["latin"] });
const space_mono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });


export const metadata: Metadata = {
  title: "Dev-finder",
  description: "Generated by create me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          space_mono.className,
          "debug-screens",
          "dark:bg-mainDark light:bg-mainLight bg-main"
        )}
        suppressHydrationWarning={true}
      >
        <LayoutContainer>{children}</LayoutContainer>
      </body>
    </html>
  );
}
