import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutContainer from "./LayoutContainer";

const spacemono = Space_Mono({
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Dev-finder",
  description: "Generated by create me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={cn(
          spacemono.className,
          "debug-screens",
          "dark:bg-mainDark light:bg-mainLight bg-main"
        )}
        suppressHydrationWarning={true}
      >
        <LayoutContainer>{children}</LayoutContainer>
      </body>
    </html>
  );
}
